.catalog:
  name: "PhpMyAdmin"
  version: "phpmyadmin-V0.1"
  description: "Web interface for MySQL and MariaDB"
  maintainer: "Nicolas Bellamy <n.bellamy@titeya.com>"
  uuid: PhpMyAdmin-0

PhpMyAdmin:
  health_check:
      port: 80
      interval: 10000
      unhealthy_threshold: 3
      request_line: GET / HTTP/1.0
      healthy_threshold: 2
      response_timeout: 10000
