.catalog:
  name: "backup"
  version: "Backup-V0.1"
  description: "Backup to FTP"
  maintainer: "Nicolas Bellamy <n.bellamy@titeya.com>"
  uuid: backup-0
  questions:
    - variable: "MYSQL_HOST"
      label: "Hote MYSQL"
      description: "Hote serveur Mysql (auto link:mysql)"
      type: "string"
      required: true
      default: "mysql"
    - variable: "MYSQL_PORT"
      label: "port MYSQL"
      description: "Port serveur Mysql"
      type: "string"
      required: true
      default: "3306"
    - variable: "MYSQL_USER"
      label: "Utilsateur MYSQL"
      description: "Utilisateur Mysql"
      type: "string"
      required: true
      default: "root"
    - variable: "MYSQL_PASS"
      label: "Mot de passe MYSQL"
      description: "Mot de passe Mysql"
      type: "string"
      required: true
    - variable: "MONGODB_HOST"
      label: "Hote MONGODB"
      description: "Hote serveur MongoDb (auto link:mongo)"
      type: "string"
      required: true
      default: "mongo"
    - variable: "MONGODB_PORT"
      label: "port MONGODB"
      description: "Port serveur MongoDb"
      type: "string"
      required: true
      default: "27017"
    - variable: "MONGODB_USER"
      label: "Utilsateur MONGODB"
      description: "Utilisateur MongoDb"
      type: "string"
      required: false
      default: ""
    - variable: "MONGODB_PASS"
      label: "Mot de passe MONGODB"
      description: "Mot de passe MongoDb"
      type: "string"
      required: false
    - variable: "FTP_HOST"
      label: "Hote FTP"
      description: "Hote serveur FTP"
      type: "string"
      required: true
      default: ""
    - variable: "FTP_PORT"
      label: "port FTP"
      description: "Port serveur FTP"
      type: "string"
      required: true
      default: "21"
    - variable: "FTP_USER"
      label: "Utilsateur FTP"
      description: "Utilisateur FTP"
      type: "string"
      required: true
      default: ""
    - variable: "FTP_PASS"
      label: "Mot de passe FTP"
      description: "Mot de passe FTP"
      type: "string"
      required: true
    - variable: "FTP_DIRECTORY"
      label: "Repertoire FTP"
      description: "Repertoire de destination FTP"
      type: "string"
      required: true
      default: "/"
    - variable: "CRON_TIME"
      label: "Tache Cron"
      description: "Evenement Cron (ex:0 0 * * *)"
      type: "string"
      required: true
      default: "0 0 * * *"
    - variable: "MAX_BACKUPS"
      label: "Nombre de backup"
      description: "Nombre de Backup"
      type: "string"
      required: true
      default: "3"
    - variable: "INIT_BACKUP"
      label: "Lancement au demarrage"
      description: "Lancer au demarrage du container ? (oui ou vide)"
      type: "string"
      default: "oui"

backup:
