composer:
  image: titeya/dockercomposer
  environment:
    COMPOSER_DB_NAME: ${MYSQL_DATABASE}
    COMPOSER_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
    MYSQL_ENV_MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  external_links:
    - mysql/mysql:mysql
    - memcached/memcache:mcserver
  volumes:
    - ${VOLUME}:/usr/share/nginx/www/html/images
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.pull_image: "always"
    io.rancher.scheduler.global: "true"
    io.rancher.scheduler.affinity:host_label: "composer=true"
