composer:
  image: registry.titeya.com:5000/titeya/composer:v1
  environment:
    COMPOSER_DB_NAME: ${MYSQL_DATABASE}
    COMPOSER_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
    MYSQL_ENV_MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  external_links:
    - galera/galera-lb:mysql
    - memcache/memcache:mcserver
  volumes:
    - ${VOLUME}:/usr/share/nginx/www/html/images
  tty: true
  stdin_open: true
  volume_driver: ${VOLUME_DRIVER}
  labels:
    io.rancher.container.pull_image: "always"
    io.rancher.scheduler.global: "true"
    io.rancher.scheduler.affinity:host_label: "composer=1"
