composer:
  image: registry.titeya.com:5000/titeya/composer
  environment:
    COMPOSER_DB_NAME: ${MYSQL_DATABASE}
    VIRTUAL_HOST: ${VIRTUAL_HOST}
  external_links:
    - pxc/pxc:mysql
  volumes:
    - ${VOLUME}:/usr/share/nginx/www/html/images
  tty: true
  stdin_open: true
  volume_driver: ${VOLUME_DRIVER}
  labels:
    io.rancher.scheduler.global: "true"
    io.rancher.scheduler.affinity:host_label: "composer=1"
