.catalog:
  name: "composer"
  version: "Composer-V0.6"
  description: "CMS and publishing platform" 
  questions:    
    - variable: "MYSQL_DATABASE"
      label: "Base MYSQL"
      description: "Nom de la base de donnée Mysql"
      type: "string"
      required: true
    - variable: "VIRTUAL_HOST"
      label: "Domaine"
      description: "Nom de domaine du site web"
      type: "string"
      required: true
    - variable: "VOLUME"
      label: "Volume"
      description: "Chemin du volume"
      type: "string"
      required: false
    - variable: "VOLUME_DRIVER"
      label: "DRIVER Volume"
      description: "Driver à utiliser pour monter le volume (ex:convoy)"
      type: "string"
      required: false
      
Composer:
