.catalog:
  name: "composer"
  version: "Composer-V0.6"
  description: "CMS and publishing platform"
  maintainer: "Nicolas Bellamy <n.bellamy@titeya.com>"
  uuid: composer-0
  questions:
    - variable: "MYSQL_ROOT_PASSWORD"
      label: "Mot de passe MYSQL"
      description: "Mot de passe administrateur Mysql (root)"
      type: "string"
      required: true
    - variable: "MYSQL_DATABASE"
      label: "Base MYSQL"
      description: "Nom de la base de donnee Mysql"
      type: "string"
      required: true
    - variable: "MYSQL_DB_PASSWORD"
      label: "Mot de passe app MYSQL"
      description: "Mot de passe de la base de donnee Mysql"
      type: "string"
      required: true
    - variable: "VOLUME"
      label: "Volume"
      description: "Chemin du volume"
      type: "string"
      required: false
    - variable: "VOLUME_DRIVER"
      label: "DRIVER Volume"
      description: "Driver a utiliser pour monter le volume (ex:convoy)"
      type: "string"
      required: false
      default: "convoy-nfs"

composer:
